[book]
authors = ["Roman Kotelnikov"]
language = "en"
multilingual = false
src = "src"
title = "Peano"

[output.html]
git-repository-url = "https://github.com/wg-romank/peano/"

[output.html.playground]
editable = true
